#!/usr/bin/env node
/** Patch js/locations.js with connection_count and recalculated great-circle distances. */

import { writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";
import { haversineKm } from "../js/utils.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const locationsPath = join(root, "js/locations.js");

const { SITE_DATA } = await import(pathToFileURL(locationsPath).href);

const auckland = SITE_DATA.meta.auckland;

function distanceForCoords(lat, lon) {
  if (lat == null || lon == null) return null;
  return Math.round(haversineKm(lat, lon, auckland.lat, auckland.lon) * 10) / 10;
}

const affiliationConnections = Object.fromEntries(
  SITE_DATA.network.affiliation.nodes.map((node) => [node.label, node.connections]),
);

const locationByAffiliation = Object.fromEntries(
  SITE_DATA.locations.map((location) => [location.affiliation, location]),
);

for (const location of SITE_DATA.locations) {
  location.connection_count = affiliationConnections[location.affiliation] || 0;
  location.distance_km = distanceForCoords(location.lat, location.lon);
}

function patchNodes(nodes) {
  for (const node of nodes) {
    if (node.lat != null && node.lon != null) {
      node.distance_km = distanceForCoords(node.lat, node.lon);
      continue;
    }
    const location = locationByAffiliation[node.affiliation];
    node.distance_km = location?.distance_km ?? null;
  }
}

patchNodes(SITE_DATA.network.individual.nodes);
patchNodes(SITE_DATA.network.affiliation.nodes);

const jsBody =
  "/** Generated by export_attendee_site_data — do not edit by hand. */\n" +
  `export const SITE_DATA = ${JSON.stringify(SITE_DATA, null, 2)};\n`;

writeFileSync(locationsPath, jsBody, "utf8");

const americas = SITE_DATA.locations.find((location) => location.lon < -50);
console.log(`Wrote ${locationsPath}`);
console.log(
  `Sample (Americas): ${americas?.affiliation} — ${americas?.distance_km} km (shortest arc)`,
);
